version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password123!"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped

  webapi:
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://+:80"
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=EventsDb;User Id=sa;Password=Password123!;TrustServerCertificate=true;"
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    restart: unless-stopped

  blazorapp:
    build:
      context: ./BlazorApp
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
    ports:
      - "8080:80"
    depends_on:
      - webapi
    restart: unless-stopped

volumes:
  sqlserver_data: