name: CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore TodoApp.sln

      - name: Build solution
        run: dotnet build TodoApp.sln --configuration Release --no-restore

      - name: Run tests (om du har)
        run: dotnet test TodoApp.sln --no-build --verbosity normal

      - name: Docker build WebAPI
        run: docker build -t securebooker-api ./WebApi

      - name: Docker build Blazor
        run: docker build -t securebooker-client ./BlazorApp